Feature/project delete
aliashkevich/AdminPanel pull request #25
Opened 2019-06-19 14:46 UTC by laura-mso

Delete projects and fetch new data without the deleted project

2019-06-19 14:50 UTC, jenna1k commented
maybe you forgot to pull before push

2019-06-19 15:00 UTC, jenna1k submitted a review, later dismissed

2019-06-20 09:32 UTC, aliashkevich requested changes

2019-06-20 09:32 UTC, aliashkevich commented on src/components/Project/ProjectTable.js
> +    const options = {
https://screencast.com/t/JNaFm0Ede6 - need to fix CORS problem, deletion doesn't work  for me

2019-06-20 11:00 UTC, wilsoncooked approved these changes

2019-06-20 14:27 UTC, aliashkevich approved these changes

2019-06-20 14:27 UTC, merged