Feature/project detail task
aliashkevich/AdminPanel pull request #50
Opened 2019-07-08 15:34 UTC by jenna1k

display assignee and status for each tasks

2019-07-08 15:59 UTC, wilsoncooked submitted a review, later dismissed
Looks great! Well done

2019-07-08 18:21 UTC, aliashkevich requested changes
Could you please also fix all img preview in Project details page (seems that they have padding-right 5px https://screencast.com/t/QhWHPbCjp1) therefore they are oval and not round.

2019-07-08 18:21 UTC, aliashkevich commented on src/components/project/ProjectTasks.js
> +      <table className='table'>
We have universal component Table.js in components/global folder. Could you please use it to avoid code duplication?

2019-07-09 07:14 UTC, aliashkevich approved these changes

2019-07-09 07:44 UTC, wilsoncooked approved these changes

2019-07-09 07:48 UTC, merged