Feature/tasks details
aliashkevich/AdminPanel pull request #64
Opened 2019-07-16 12:43 UTC by Wils0nC00k

2019-07-16 15:24 UTC, jenna1k submitted a review, later dismissed
wow looks amazing!!

2019-07-16 19:27 UTC, aliashkevich requested changes
New Task functionality doesn't work in this PR

2019-07-17 07:33 UTC, laura-mso commented on src/components/task/TaskDetailCard.js
> +                      <ProjectInfo projectId={this.state.task.projectId} />
so nice that you added a link to the project!

2019-07-17 08:00 UTC, laura-mso reviewed
The result looks really great!

2019-07-17 08:00 UTC, laura-mso commented on src/components/task/ProjectInfo.js
> +                  ? this.state.projects.find(
like this you have to do the find operation twice. maybe you can assign it to a variable above and than use that one here twice

2019-07-17 08:01 UTC, Wils0nC00k commented on src/components/task/ProjectInfo.js
> +                  ? this.state.projects.find(
I couldn't work out how to do this inside the return :/ If you have an idea please let me know

2019-07-17 09:49 UTC, laura-mso commented on src/components/task/ProjectInfo.js
> +                  ? this.state.projects.find(
I think you can create the variable above the return

2019-07-22 10:36 UTC, aliashkevich approved these changes
well done)

2019-07-22 12:07 UTC, merged