Cleanup of one point tickets
aliashkevich/AdminPanel pull request #67
Opened 2019-07-23 11:58 UTC by Wils0nC00k

=> Removed new user button
=> Remove word 'Dashboard' at top of the screen
=> Implemented logos on all tables
=> Real data on dashboard small cards
=> Resized login

2019-07-23 11:59 UTC, Wils0nC00k commented
The logo on login not centred will be fixed with Anastasia's branch

2019-07-24 11:39 UTC, aliashkevich submitted a review, later dismissed

2019-07-24 11:48 UTC, laura-mso requested changes

2019-07-24 11:48 UTC, laura-mso commented on src/components/client/ClientNew.js
> +  componentWillUpdate() {}
```suggestion
```

2019-07-24 11:55 UTC, laura-mso approved these changes
Great thank you!

2019-07-24 11:57 UTC, merged